print("matching "+(10e2))
print("actual   "+CONFIG::var1)
print("matching "+(15e-13))
print("actual   "+CONFIG::var2)
print("matching "+(10e-2))
print("actual   "+CONFIG::var3)
print("hex form "+CONFIG::var4)