const int p_A_m = 1;
const int p_A_private_n = 2;
const int p_A_p_o = 3;
const int abcclass_p_A = 0;
const int native_abc_length = 166;
const int native_abc_method_count = 4;
const int native_abc_class_count = 1;
const int native_abc_script_count = 1;
extern const unsigned char native_abc_data[];
